packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@firebase/util'
  - 'protobufjs'
  - 'esbuild'
  - '@esbuild/darwin-arm64'
  - '@esbuild/darwin-x64'
  - '@esbuild/linux-x64'
  - '@esbuild/linux-x64-gnu'
  - '@esbuild/android-arm64'
  - '@esbuild/win32-x64'
